# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c24a98bc184377250a094abb9e465fdde9d03f274cc21f0aa9306ebac16bc06768c7ef55f3714fd66afc5b65c268c567867a86574f80a4a49d6af67bc7ccc2a1

test:
  secret_key_base: 5324066f444fd284375b612418d2e2f2fbb39d7314b6d2a5487623603a4e15ef4595c377071b8be7a79b31458b50751bd004c01b8c773dcff1477ee0c13393cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
